import 'dart:convert';
import 'dart:math' as math;

import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:intl/intl.dart';
import 'package:timeago/timeago.dart' as timeago;
import 'lat_lng.dart';
import 'place.dart';
import 'uploaded_file.dart';
import '/backend/backend.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import '/backend/schema/structs/index.dart';
import '/backend/schema/enums/enums.dart';
import '/auth/firebase_auth/auth_util.dart';

List<String>? hobbieSelector() {
  final commonHobbies = [
    "Reading",
    "Writing",
    "Drawing",
    "Listening to Music",
    "Playing Music",
    "Cooking",
    "Gardening",
    "DIY Crafts",
    "Photography",
    "Video Gaming",
    "Outdoor Activities",
    "Sports",
    "Nature Exploration",
    "Socializing",
    "Volunteering",
    "Traveling",
    "Mindfulness",
    "Meditation",
    "Yoga",
    "Relaxation",
    "Pleasure Reading",
    "Nature Appreciation",
    "Playing with Pets",
    "Intellectual Pursuits",
    "History",
    "Non-fiction Reading",
    "Documentaries",
    "Online Learning",
    "Artistic Expression",
    "Music",
    "Visual Arts",
    "Digital Creations",
    "Board Games",
    "Card Games",
    "Trivia Games",
    "Puzzles",
    "Coding and Technology",
    "Web Development",
    "App Development",
    "Game Development",
    "Graphic Design",
    "Home Projects",
    "Exploring Culinary Arts",
    "Financial Awareness",
    "Investing",
    "Budgeting",
    "Saving Money",
    "Stargazing",
    "Playing Instruments",
    "Singing",
    "Dancing",
    "Watching Movies",
    "Learning New Languages",
    "Spending Time with Family",
    "Going to Concerts",
    "Hiking",
    "Camping",
    "Fishing",
    "Swimming",
    "Biking",
    "Running",
    "Working Out",
    "Playing Sports",
    "Birdwatching",
    "Trying New Foods",
    "Playing Board Games",
    "Solving Brain Teasers",
    "Building Websites",
    "Creating Apps",
    "Playing Card Games",
    "Geocaching",
    "Urban Exploration",
    "People Watching",
    "Cloud Watching",
    "Journaling",
    "Playing Trivia Games",
    "Redecorating",
    "Upcycling",
    "Learning About Different Cultures",
    "Home Improvement",
    "Decluttering",
    "Attending Workshops",
    "Listening to Podcasts",
    "Binge-watching TV Shows",
    "Shopping",
    "Going to the Spa",
    "Taking a Nap",
    "Spending Time in Nature",
    "Napping",
    "Getting Massages",
    "Playing Strategy Games",
    "Learning to Code",
    "Solving Puzzles",
    "Investigating History",
    "Playing Escape Rooms",
    "Trying New Recipes",
    "Organizing",
    "Repurposing",
    "Playing Trivia Games",
    "Learning Personal Finance",
    "Collecting Items",
    "Exploring New Places",
    "Creating Games",
    "Learning about Personal Finance",
    "Investing",
    "Budgeting",
    "Saving Money",
  ];

  return commonHobbies;
}

int? strtoint(String str) {
  try {
    int result = int.parse(str);
    return result;
  } catch (e) {
    return null;
  }
}

DateTime? yesterdaydate() {
  DateTime currentDate = DateTime.now();
  DateTime yesterdayDate = currentDate.subtract(Duration(days: 1));
  return yesterdayDate;
}

DateTime? tomorrowdate() {
  DateTime currentDate = DateTime.now();
  DateTime tomorrowDate = currentDate.add(Duration(days: 1));
  return tomorrowDate;
}

String getPlaybackIDfromURL(String url) {
  String strl = url.replaceAll(".m3u8", "");
  return strl.split("/").last;
}

List<String> placeSelector() {
  return [
    "Mumbai, Maharashtra, India",
    "Delhi, Delhi, India",
    "Bangalore, Karnataka, India",
    "Hyderabad, Telangana, India",
    "Chennai, Tamil Nadu, India",
    "Kolkata, West Bengal, India",
    "New York City, New York, USA",
    "Los Angeles, California, USA",
    "Chicago, Illinois, USA",
    "Houston, Texas, USA",
    "Phoenix, Arizona, USA",
    "Beijing, China",
    "Shanghai, China",
    "Guangzhou, China",
    "Shenzhen, China",
    "Chengdu, China",
    "Moscow, Russia",
    "Saint Petersburg, Russia",
    "Novosibirsk, Russia",
    "Yekaterinburg, Russia",
    "Kazan, Russia",
    "Karachi, Sindh, Pakistan",
    "Lahore, Punjab, Pakistan",
    "Faisalabad, Punjab, Pakistan",
    "Rawalpindi, Punjab, Pakistan",
    "Islamabad, Islamabad Capital Territory, Pakistan",
    "Dhaka, Bangladesh",
    "Chittagong, Bangladesh",
    "Khulna, Bangladesh",
    "Rajshahi, Bangladesh",
    "Sylhet, Bangladesh",
    "Colombo, Western Province, Sri Lanka",
    "Kandy, Central Province, Sri Lanka",
    "Galle, Southern Province, Sri Lanka",
    "Jaffna, Northern Province, Sri Lanka",
  ];
}

String getRandomBambooQuote() {
  final List<String> bambooQuotes = [
    "I'm not lazy, I'm just conserving energy for the bamboo feast later.",
    "Why rush through life when you can snooze through it?",
    "You say 'lazy', I say 'efficient'.",
    "I'm not sleeping, I'm meditating horizontally.",
    "Life is short, but so are my waking hours.",
    "They call it 'lazy', I call it 'bamboo time'.",
    "I dream of bamboo forests and long naps.",
    "In a world full of hustle, I'm just here for the bamboo buffet.",
    "Why do today what you can put off until tomorrow?",
    "Sleeping is my cardio.",
    "Some call it laziness, I call it 'bamboo appreciation'.",
    "The early panda catches the... Zzz...",
    "I'm not avoiding responsibilities, I'm exploring the dream world.",
    "I'm not slow, I'm just enjoying the journey.",
    "Sleeping beauty got nothing on this panda.",
    "Dreaming of a world where bamboo grows on trees... oh wait.",
    "I'll wake up when the bamboo arrives.",
    "I'm not slacking off, I'm just strategically recharging.",
    "If only bamboo grew on pillows, I'd never leave my bed.",
    "Life is too short to wake up early.",
  ];

  final math.Random random = math.Random();
  final int index = random.nextInt(bambooQuotes.length);
  return bambooQuotes[index];
}

String? dayStreakFind(DateTime downloadDate) {
  /// replace with actual download date
  DateTime now = DateTime.now();
  Duration difference = now.difference(downloadDate);
  int days = difference.inDays;
  return days.toString() == '0' ? '1' : days.toString();

  // write a function to find the number days the app being downloaded till now
}

String taskheading3(String key) {
  final Map<String, String> taskHeadings = {
    '1': 'Write a letter to your younger self, offering love and encouragement',
    '2': 'Create a vision board of your dreams and aspirations',
    '3': 'Volunteer for a cause you\'re passionate about',
    '4': 'Try a new hobby or skill that excites you',
    '5': 'Practice forgiveness towards yourself and others',
    '6': 'Attend a support group meeting and share your story',
    '7': 'Engage in a self-compassion meditation practice',
    '8': 'Plan a day trip to a place you\'ve always wanted to visit',
    '9': 'Create a self-care routine and commit to practicing it daily',
    '10': 'Start a gratitude journal and write in it regularly',
    '11': 'Attend a workshop or seminar on personal growth',
    '12': 'Explore your creative side through art or writing',
    '13': 'Practice mindfulness meditation for inner peace',
    '14': 'Set boundaries in your relationships and stick to them',
    '15': 'Join a book club or discussion group',
    '16': 'Take a class or course to learn something new',
    '17': 'Attend therapy sessions to work through past trauma',
    '18': 'Plan a weekend getaway to relax and recharge',
    '19': 'Engage in physical exercise to boost your mood',
    '20': 'Practice deep breathing exercises for relaxation',
    '21': 'Start a small project that brings you joy',
    '22': 'Connect with friends or family members for support',
    '23': 'Attend a meditation retreat for inner healing',
    '24': 'Create a daily affirmation practice to build self-esteem',
    '25': 'Spend time in nature to rejuvenate your spirit',
    '26': 'Join a community organization or club',
    '27': 'Take up gardening as a therapeutic activity',
    '28': 'Explore your spirituality through prayer or meditation',
    '29': 'Engage in acts of kindness towards others',
    '30': 'Practice positive self-talk and affirmations',
    '31': 'Attend a workshop on self-love and acceptance',
    '32': 'Participate in a group therapy session',
    '33': 'Plan a self-care day filled with activities you enjoy',
    '34': 'Set realistic goals for yourself and work towards them',
    '35': 'Explore alternative healing modalities such as acupuncture or reiki',
    '36': 'Create a sacred space in your home for reflection and meditation',
    '37': 'Take a cooking or baking class to learn new recipes',
    '38': 'Engage in journaling as a form of self-expression',
    '39': 'Practice forgiveness towards yourself and others',
    '40': 'Attend a workshop on resilience and coping strategies',
    '41': 'Join a support group for survivors of sexual trauma',
    '42': 'Plan a day of pampering and self-indulgence',
    '43': 'Take up a creative hobby like painting or pottery',
    '44': 'Explore mindfulness-based stress reduction techniques',
    '45': 'Create a playlist of uplifting and empowering songs',
    '46': 'Engage in volunteer work to give back to your community',
    '47': 'Attend a therapy session focusing on self-esteem',
    '48': 'Join a social club or meetup group to meet new people',
    '49': 'Practice self-care by getting enough sleep each night',
    '50': 'Celebrate your progress and achievements, no matter how small',
    '51': 'Plan a day of relaxation and self-reflection',
    '52': 'Attend a seminar on trauma recovery and resilience',
    '53': 'Explore mindfulness-based cognitive therapy techniques',
    '54': 'Take up a mindfulness-based stress reduction course',
    '55': 'Engage in positive visualization exercises for self-confidence',
    '56': 'Attend a workshop on self-compassion and self-love',
    '57': 'Create a self-care toolkit with items that bring you comfort',
    '58': 'Practice gratitude by acknowledging the good in your life',
    '59': 'Attend a therapy session focusing on inner child work',
    '60': 'Join a support group for survivors of sexual abuse',
    '61': 'Plan a weekend retreat to focus on your healing journey',
    '62': 'Explore trauma-informed yoga practices for relaxation',
    '63': 'Take up a mindfulness-based meditation course',
    '64': 'Engage in a therapy session focusing on empowerment',
    '65': 'Attend a seminar on building resilience after trauma',
    '66': 'Practice self-care by setting boundaries in your relationships',
    '67': 'Join a trauma-informed therapy group for survivors',
    '68': 'Plan a day of self-care activities to nurture yourself',
    '69': 'Explore trauma-focused cognitive behavioral therapy techniques',
    '70': 'Take up a mindfulness-based stress reduction workshop',
    '71': 'Attend a support group focusing on healing and growth',
    '72': 'Join a trauma-informed yoga class for relaxation',
    '73': 'Plan a nature retreat to connect with the earth and yourself',
    '74': 'Explore mindfulness-based cognitive therapy practices',
    '75': 'Engage in a therapy session focusing on self-compassion',
    '76': 'Attend a seminar on rebuilding trust after trauma',
    '77': 'Practice self-care by prioritizing your needs and well-being',
    '78': 'Join a trauma-informed therapy group for survivors',
    '79': 'Plan a weekend getaway to a peaceful destination',
    '80': 'Explore mindfulness-based stress reduction techniques',
    '81': 'Take up a mindfulness-based meditation course',
    '82': 'Engage in a therapy session focusing on inner healing',
    '83': 'Attend a seminar on building resilience after trauma',
    '84': 'Practice self-care by setting boundaries in your relationships',
    '85': 'Join a trauma-informed therapy group for survivors',
    '86': 'Plan a day of self-care activities to nurture yourself',
    '87': 'Explore trauma-focused cognitive behavioral therapy techniques',
    '88': 'Take up a mindfulness-based stress reduction workshop',
    '89': 'Attend a support group focusing on healing and growth',
    '90': 'Join a trauma-informed yoga class for relaxation',
    '91': 'Plan a nature retreat to connect with the earth and yourself',
    '92': 'Explore mindfulness-based cognitive therapy practices',
    '93': 'Engage in a therapy session focusing on self-compassion',
    '94': 'Attend a seminar on rebuilding trust after trauma',
    '95': 'Practice self-care by prioritizing your needs and well-being',
    '96': 'Join a trauma-informed therapy group for survivors',
    '97': 'Plan a weekend getaway to a peaceful destination',
    '98': 'Explore mindfulness-based stress reduction techniques',
    '99': 'Take up a mindfulness-based meditation course',
    '100': 'Engage in a therapy session focusing on inner healing',
  };
  return taskHeadings[key] ?? 'Task';
}

String morningTask(String key) {
  final Map<String, String> taskHeadings = {
    '1': 'Practice gratitude: Write down 3 things you\'re thankful for',
    '2': 'Affirm yourself: Positive statements in front of mirror',
    '3': 'Deep breathing: Center yourself in 10 minutes',
    '4': 'Nutritious breakfast: Fuel body and mind for the day',
    '5': 'Brief morning walk: Soak in sunlight',
    '6': 'Uplifting music/podcast: Get ready with motivation',
    '7': 'Set achievable goals: Visualize accomplishing them',
    '8': 'Journal reflection: Intentions and aspirations for the day',
    '9': 'Gentle yoga/stretching: Awaken body and mind',
    '10': 'Connect with loved one: Morning encouragement',
    '11': 'Inspiring quote: Uplift your spirits',
    '12': 'Morning routine: Self-care and affirming activities',
    '13': 'Meditation: Cultivate inner peace and resilience',
    '14': 'Self-love expression: Favorite hobby or activity',
    '15': 'Visualize overcoming challenges: Thrive in day ahead',
    '16': 'Boost self-esteem: Write down one admired quality',
    '17': 'Positive intention: Carry it with you all day',
    '18': 'Grounding exercises: Establish stability and security',
    '19': 'Energize with workout: Brief physical activity',
    '20': 'Gratitude jar: Add a morning note of thanks',
    '21': 'Mindful tea/coffee ritual: Savor mindfully',
    '22': 'Morning affirmation: Start with positivity',
    '23': 'Visualization exercise: Succeed and thrive',
    '24': 'Encouraging letter to self: Read each morning',
    '25': 'Dance to upbeat song: Invigorate your mood',
    '26': 'Positive self-talk: Affirm strengths and capabilities',
    '27': 'Vision board creation: Represent hopes and dreams',
    '28': 'Appreciate nature\'s beauty: Outside your window',
    '29': 'Mindfulness practice: Focus on breath',
    '30': 'Gratitude prayer/reflection: Start your day',
    '31': 'Cultivate optimism: Write one thing you\'re looking forward to',
    '32': 'Uplifting morning playlist: Inspire and motivate',
    '33': 'Morning journaling: Capture thoughts and feelings',
    '34': 'Visualize successful day: Quick exercise',
    '35': 'Inner child connection: Engage in play',
    '36': 'Empowering affirmations: Prepare for the day',
    '37': 'Morning courage intention: Approach challenges boldly',
    '38': 'Mindful eating: Savor breakfast bites',
    '39': 'Guided meditation: Confidence and empowerment',
    '40': 'Morning gratitude ritual: Express thanks',
    '41': 'Morning stretch routine: Awaken body and mind',
    '42': 'Nature walk: Connect with the earth',
    '43': 'Cultivate self-compassion: Write one thing you love about yourself',
    '44': 'Visualization of goals: Confidence boost',
    '45': 'Peaceful day visualization: Start mornings',
    '46': 'Affirmation mantra: Boost self-confidence',
    '47': 'Calm with deep breathing: Ease nerves',
    '48': 'Celebrate progress: Write down one proud accomplishment',
    '49': 'Graceful morning intention: Face challenges resiliently',
    '50': 'Positive outlook: Start with a smile',
    '51': 'Mind-clearing walk: Energize body and mind',
    '52': 'Gratitude meditation: Cultivate abundance',
    '53': 'Encouraging self-letter: Read aloud daily',
    '54': 'Visualization for goals: Manifest aspirations',
    '55': 'Intention setting: Align with values',
    '56': 'Morning yoga practice: Connect body and breath',
    '57': 'Reflective morning routine: Gratitude included',
    '58': 'Morning journaling session: Explore thoughts',
    '59': 'Uplifting podcast/audiobook: Morning routine',
    '60': 'Morning prayer/spiritual practice: Start your day',
    '61': 'Visualization to boost confidence: Morning exercise',
    '62': 'Foster self-love: Appreciate one thing about yourself',
    '63': 'Affirmation board creation: Empowering quotes/images',
    '64': 'Acknowledge strengths: Practice self-compassion',
    '65': 'Resilient morning intention: Face challenges',
    '66': 'Morning stretching: Release tension',
    '67': 'Cultivate anticipation: Write one thing you\'re excited about',
    '68': 'Nature walk: Connect with beauty around you',
    '69': 'Guided meditation: Clarity and focus',
    '70': 'Mindfulness practice: Observe without judgment',
    '71': 'Self-care morning routine: Include reflection',
    '72': 'Value-based intentions: Prioritize goals',
    '73': 'Morning gratitude: Express thanks',
    '74': 'Cultivate optimism: Write one thing you\'re looking forward to',
    '75': 'Visualization for goals: Manifest aspirations',
    '76': 'Self-affirmations: Boost confidence',
    '77': 'Mindfulness meditation: Start calmly',
    '78': 'Movement and exercise: Include in routine',
    '79': 'Personal/professional intentions: Align goals',
    '80': 'Foster self-love: Appreciate one thing about yourself',
    '81': 'Morning reflection: Connect with inner wisdom',
    '82': 'Grounding with deep breathing: Reduce stress',
    '83': 'Gratitude journaling: Cultivate appreciation',
    '84': 'Self-care routine: Include nourishment',
    '85': 'Inspiring intentions: Motivate action',
    '86': 'Celebrate achievements: Write down one proud moment',
    '87': 'Boost confidence: Morning visualization',
    '88': 'Challenge negative self-talk: Build resilience',
    '89': 'Mindfulness practice: Increase awareness',
    '90': 'Creativity and self-expression: Include in routine',
    '91': 'Well-being intentions: Prioritize happiness',
    '92': 'Grateful morning start: Appreciate one thing',
    '93': 'Grounding exercise: Connect with earth',
    '94': 'Treat yourself with kindness: Practice self-compassion',
    '95': 'Visualize success: Morning exercise',
    '96': 'Relaxation and rejuvenation: Include in routine',
    '97': 'Value-aligned intentions: Aspirations',
    '98': 'Cultivate enthusiasm: Write one thing you\'re excited about',
    '99': 'Morning meditation: Cultivate peace and clarity',
    '100': 'Morning gratitude: Acknowledge blessings'
  };
  return taskHeadings[key] ?? 'Task';
}

String taskheading1(String key) {
  final Map<String, String> taskHeadings = {
    '1': 'Sip warm tea and relax',
    '2': 'Write down 3 things you\'re grateful for',
    '3': 'Listen to calming music and focus on your breath',
    '4': 'Read a few pages of an uplifting book',
    '5': 'Stretch and breathe deeply for 5 minutes',
    '6': 'Color in a coloring book for 10 minutes',
    '7': 'Enjoy a delicious snack in a peaceful environment',
    '8': 'Light a scented candle and relax for 15 minutes',
    '9': 'Spend 5 minutes decluttering a small area',
    '10': 'Do some gentle yoga stretches',
    '11': 'Write a short positive affirmation for yourself',
    '12': 'Do a quick puzzle or brain teaser',
    '13': 'Take a relaxing bath or shower',
    '14': 'Diffuse your favorite essential oil',
    '15': 'Savor a piece of dark chocolate',
    '16': 'Take a short walk around your neighborhood',
    '17': 'Write a short note to a loved one',
    '18': 'Do some light housework to clear your head',
    '19': 'Enjoy a cup of refreshing herbal tea',
    '20': 'Take a break and browse inspiring content online',
    '21': 'Practice mindful breathing for a few minutes',
    '22': 'Smile at yourself in the mirror',
    '23': 'Organize your desk or workspace',
    '24': 'Do some jumping jacks or light cardio for 5 minutes',
    '25': 'Play a quick game of solitaire',
    '26': 'Write down 3 good things that happened today',
    '27': 'Do some light gardening or tend to your houseplants',
    '28': 'Do some gentle neck rolls to release tension',
    '29': 'Enjoy a refreshing glass of lemonade',
    '30': 'Light some incense and meditate for 5 minutes',
    '31': 'Do some gentle calf raises to improve circulation',
    '32': 'Organize your notes or to-do list',
    '33': 'Watch a short video about nature',
    '34': 'Play a quick round of a word game',
    '35': 'Do some ankle circles to improve flexibility',
    '36': 'Enjoy a refreshing fruit smoothie',
    '37': 'Light some scented candles and listen to calming music',
    '38': 'Do some gentle wrist stretches to release tension',
    '39': 'Organize your inbox and delete unnecessary emails',
    '40': 'Watch a short video about mindfulness',
    '41': 'Play a quick round of Tic-Tac-Toe',
    '42': 'Do some gentle hip circles to improve flexibility',
    '43': 'Enjoy a refreshing cup of iced tea',
    '44': 'Light some calming candles and read a few pages of a book',
    '45': 'Do some gentle shoulder rolls to release tension',
    '46': 'Declutter your bag or purse for better organization',
    '47': 'Watch a short video about gratitude',
    '48': 'Play a quick round of memory game',
    '49': 'Do some finger stretches to improve dexterity',
    '50': 'Enjoy a delicious yogurt parfait',
    '51': 'Listen to an audiobook for a few minutes',
    '52': 'Write down your goals for the day',
    '53': 'Do some light facial exercises to reduce tension',
    '54': 'Enjoy a refreshing cup of fruit juice',
    '55': 'Light some scented candles and journal your thoughts',
    '56': 'Do some gentle arm circles to improve flexibility',
    '57': 'Organize your desktop files and folders',
    '58': 'Watch a short video about self-care',
    '59': 'Play a relaxing game like Tetris',
    '60': 'Do some simple toe stretches to improve flexibility',
    '61': 'Enjoy a healthy snack like nuts and seeds',
    '62': 'Take a few deep breaths of fresh air',
    '63': 'Listen to calming nature sounds',
    '64': 'Do some light hamstring stretches',
    '65': 'Write in a gratitude journal',
    '66': 'Draw or doodle soothing images',
    '67': 'Create a calming music playlist',
    '68': 'Practice deep breathing exercises',
    '69': 'Enjoy a warm cup of herbal tea',
    '70': 'Take a leisurely nature walk',
    '71': 'Cuddle with a beloved pet',
    '72': 'Watch a comforting movie or show',
    '73': 'Try gentle guided meditation',
    '74': 'Create a vision board for healing',
    '75': 'Listen to uplifting podcasts',
    '76': 'Engage in gentle stretching routines',
    '77': 'Write letters to your inner child',
    '78': 'Practice self-compassion affirmations',
    '79': 'Create a cozy reading nook',
    '80': 'Engage in mindful art therapy',
    '81': 'Dance freely to soothing music',
    '82': 'Plant and nurture indoor plants',
    '83': 'Practice grounding techniques',
    '84': 'Create a comfort food recipe',
    '85': 'Watch calming nature documentaries',
    '86': 'Engage in gentle guided imagery',
    '87': 'Create a calming bedtime routine',
    '88': 'Write poetry or expressive prose',
    '89': 'Engage in gentle self-massage',
    '90': 'Engage in light aromatherapy',
    '91': 'Create a playlist of favorite songs',
    '92': 'Practice loving-kindness meditation',
    '93': 'Spend time in a sensory garden',
    '94': 'Take a soothing candlelit bath',
    '95': 'Engage in mindful body scanning',
    '96': 'Create a self-care jar of activities',
    '97': 'Engage in gentle yin yoga',
    '98': 'Visualize a safe, peaceful place',
    '99': 'Engage in compassionate self-talk',
    '100': 'Spend time stargazing or cloud-watching'
    // Add headings for other tasks here
  };
  return taskHeadings[key] ?? 'Task';
}

String taskheading2(String key) {
  final Map<String, String> taskHeadings = {
    '1': 'Practice deep breathing for relaxation and calmness',
    '2': 'Enjoy a soothing cup of herbal tea',
    '3': 'Take a leisurely walk in nature',
    '4': 'Write down positive affirmations for yourself',
    '5': 'Listen to your favorite calming music playlist',
    '6': 'Engage in a mindful meditation session',
    '7': 'Take a warm bath with essential oils',
    '8': 'Spend quality time with a beloved pet',
    '9': 'Try a new hobby or creative activity',
    '10': 'Read a book that brings you joy',
    '11': 'Practice gentle yoga for relaxation and flexibility',
    '12': 'Enjoy a healthy and nourishing meal',
    '13': 'Create a gratitude journal and write daily entries',
    '14': 'Do a digital detox for a few hours',
    '15': 'Dance to your favorite uplifting music',
    '16': 'Practice mindfulness while doing household chores',
    '17': 'Watch a feel-good movie or TV show',
    '18': 'Take time to appreciate nature and its beauty',
    '19': 'Do a 10-minute guided relaxation exercise',
    '20': 'Connect with a friend or loved one',
    '21': 'Practice self-massage or gentle self-care rituals',
    '22': 'Spend time outdoors and soak up sunshine',
    '23': 'Create a vision board of your dreams and goals',
    '24': 'Try a new recipe and enjoy cooking',
    '25': 'Engage in deep stretching exercises for relaxation',
    '26': 'Write a letter to your future self',
    '27': 'Do a random act of kindness for someone else',
    '28': 'Practice mindfulness while eating a meal',
    '29': 'Try aromatherapy with calming scents',
    '30': 'Engage in a creative art or craft project',
    '31': 'Do a 30-minute home workout session',
    '32': 'Explore a nearby park or botanical garden',
    '33':
        'Learn a new relaxation technique, such as progressive muscle relaxation',
    '34': 'Do a guided imagery exercise for relaxation',
    '35': 'Take a break and enjoy a cup of hot cocoa',
    '36': 'Do a digital decluttering session',
    '37': 'Create a calming bedtime routine for better sleep',
    '38': 'Practice gratitude by listing things you\'re thankful for',
    '39': 'Try a mindfulness walking meditation',
    '40': 'Create a cozy reading nook and read a book',
    '41': 'Enjoy a mindful eating experience with your favorite snack',
    '42': 'Try a relaxation app or guided meditation',
    '43': 'Do a gentle body scan meditation for relaxation',
    '44': 'Take a nap and allow yourself to rest',
    '45': 'Engage in deep belly breathing to calm the mind',
    '46': 'Do a gentle morning stretch routine',
    '47': 'Create a playlist of uplifting and calming music',
    '48': 'Try a laughter yoga session for joy and relaxation',
    '49': 'Engage in a mindful listening exercise',
    '50': 'Write down your worries and then let them go',
    '51': 'Spend time in your favorite outdoor spot',
    '52': 'Do a gratitude meditation to focus on positivity',
    '53': 'Try a progressive relaxation exercise for stress relief',
    '54': 'Engage in a guided self-compassion meditation',
    '55': 'Create a calming environment with soft lighting and candles',
    '56': 'Practice mindful breathing before bedtime for better sleep',
    '57': 'Do a 10-minute guided loving-kindness meditation',
    '58': 'Create a self-care kit with your favorite comforting items',
    '59': 'Try a gentle foam rolling session for relaxation',
    '60': 'Engage in a mindful body scan before starting your day',
    '61': 'Spend time in a quiet space for reflection and solitude',
    '62': 'Do a gentle stretching routine to release tension',
    '63': 'Try a mindful eating exercise with a piece of chocolate',
    '64': 'Engage in a deep relaxation visualization exercise',
    '65': 'Create a self-love affirmation mantra and repeat it daily',
    '66': 'Do a guided mountain meditation for inner strength',
    '67': 'Practice mindfulness while sipping a cup of tea',
    '68': 'Try a 5-minute meditation break during your workday',
    '69': 'Engage in a mindful listening exercise with calming music',
    '70': 'Create a gratitude jar and fill it with daily blessings',
    '71': 'Try a gentle yoga flow for relaxation and stress relief',
    '72': 'Engage in a mindful breathing exercise for anxiety relief',
    '73': 'Do a 10-minute guided body scan meditation',
    '74': 'Practice self-compassion by writing yourself a love letter',
    '75': 'Create a nature-inspired relaxation corner in your home',
    '76': 'Try a mindfulness-based stress reduction exercise',
    '77': 'Engage in a loving-kindness meditation for inner peace',
    '78': 'Do a deep relaxation body scan before bedtime',
    '79': 'Practice mindful eating with a piece of fruit',
    '80': 'Create a gratitude collage with images and quotes',
    '81': 'Try a guided progressive muscle relaxation exercise',
    '82': 'Engage in a 10-minute mindfulness meditation',
    '83': 'Do a mindful walk in nature, focusing on your surroundings',
    '84': 'Practice self-compassion by acknowledging your emotions',
    '85': 'Try a grounding exercise to feel centered and calm',
    '86': 'Engage in a deep breathing exercise for stress relief',
    '87': 'Create a vision board of your ideal self and future',
    '88': 'Practice mindfulness while enjoying a hot shower',
    '89': 'Do a gentle yoga nidra meditation for relaxation',
    '90': 'Engage in a gratitude visualization exercise',
    '91': 'Try a mindful body scan to release tension',
    '92': 'Practice self-compassion by speaking kindly to yourself',
    '93': 'Do a 5-minute guided loving-kindness meditation',
    '94': 'Engage in a deep relaxation visualization for sleep',
    '95': 'Try a mindfulness-based stress reduction body scan',
    '96': 'Practice self-compassion by giving yourself a hug',
    '97': 'Do a 10-minute mindfulness meditation on gratitude',
    '98': 'Engage in a grounding exercise to feel present',
    '99': 'Try a guided imagery meditation for inner peace',
    '100': 'Practice deep breathing to calm your mind and body',
  };
  return taskHeadings[key] ?? 'Task';
}

String affirmationsLogic() {
  final affirmations = [
    'You are doing great!',
    'Keep up the good work!',
    'You are making progress!',
    'Believe in yourself!',
    'You are capable of amazing things!',
    'You are worthy and deserving of love and happiness!',
    'You are strong and resilient!',
    'You have the power to overcome any obstacle!',
    'You are a valuable and important person!',
    'You are enough just as you are!',
  ];

  final random = math.Random();
  final index = random.nextInt(affirmations.length);
  return affirmations[index];
}
